theme: jekyll-theme-minimal

title: World Cuisine League - Russia

description: 
World Cuisine League is a social online event organized by Bizkaia Talent aimed at bringing together international professionals in Bizkaia to share their favourite national recipes and, more importantly, to share their experiences and tips about relocation
